export const content = {
  nav: {
    how: "How it works",
    features: "Features",
    story: "Story",
    award: "Recognition",
    faq: "FAQ",
    cta: "Launch Smartboard",
    menu: "Menu",
  },
  hero: {
    badge: "2nd place worldwide · Gemma 4 Good Hackathon by Google",
    h1a: "Teach out loud.",
    h1b: "The board listens.",
    sub: "TRIDO is the AI smartboard you run entirely with your voice. Say what you want to teach — it draws the mind map, writes the notes and opens the timer while your eyes stay on your students.",
    cta1: "Launch Smartboard",
    cta2: "Watch it work",
    meta: ["Voice-first", "Cloud + offline mode", "English & Bahasa Indonesia"],
    try: "Try it — pick a lesson",
  },
  demo: {
    classroom: "Digital Classroom",
    cloud: "Cloud Mode",
    assistant: "Assistant",
    share: "Share",
    save: "Save",
    teacher: "Teacher",
    classLead: "Class instructor",
    ready: "All systems ready",
    readySub: "Voice ready · tap a lesson",
    listening: "Listening",
    listeningSub: "Speak naturally",
    thinking: "AI agent responding",
    thinkingSub: "Planning the board",
    done: "Done on the board",
    doneSub: "Edit, present or export",
    tabs: ["Mind map", "Document", "Classroom tools"],
    say: [
      "Make a mind map about poetry",
      "Summarize the basic accounting equation",
      "Start a five minute timer and open the scoreboard",
    ],
    mm: {
      title: "Poetry — concept map",
      center: "Poetry",
      elements: "Elements",
      inner: "Inner",
      innerSub: "Theme, mood, message",
      outer: "Outer",
      outerSub: "Diction, imagery, rhyme",
      types: "Types",
      old: "Old poetry",
      oldSub: "Pantun, Syair, Gurindam",
      modern: "Modern",
      modernSub: "Ballad, Ode, Epigram",
    },
    doc: {
      label: "Study document",
      title: "Basic Accounting Equation",
      intro:
        "The basic accounting equation is the foundation of double-entry bookkeeping for any business.",
      h1: "1. Core formula",
      formula: "Assets = Liabilities + Equity",
      h2: "2. Key components",
      items: [
        ["Assets", "what the business owns"],
        ["Liabilities", "what it owes"],
        ["Equity", "the owners' claim"],
      ],
    },
    tools: {
      timer: "Timer",
      score: "Scoreboard",
      teams: ["Team A", "Team B", "Team C"],
    },
  },
  marquee: [
    "Make a mind map about the water cycle",
    "Start a five minute timer",
    "Summarize chapter three",
    "Open the random wheel",
    "Quiz the class on fractions",
    "Show the periodic table",
    "Take attendance",
    "Graph y equals x squared",
    "Convert 5 kilometres to miles",
    "Add a new page",
  ],
  how: {
    pill: "01",
    kicker: "How it works",
    title: "From a sentence to a lesson.",
    steps: [
      {
        t: "Speak",
        d: "Press the mic, or just talk. TRIDO listens in English or Bahasa Indonesia.",
      },
      {
        t: "Understand",
        d: "An AI agent works out what you mean — a diagram, a summary, a tool — and plans the board.",
      },
      {
        t: "Appear",
        d: "Content lands on the canvas, ready to move, edit, present, share or export.",
      },
    ],
  },
  features: {
    pill: "02",
    kicker: "What's on the board",
    title: "Everything a lesson needs. Nothing to tap through.",
    mm: {
      t: "Concept maps on command",
      d: "Name a topic. TRIDO lays out branches, colours and links — and you can keep editing by hand.",
    },
    doc: {
      t: "Notes that write themselves",
      d: "Structured study documents with headings and formulas, ready to present or export.",
    },
    widgets: {
      t: "11 classroom widgets",
      d: "Ask for a tool and it opens on the board.",
      list: [
        "Calculator",
        "Timer",
        "Notes",
        "AI Quiz",
        "Converter",
        "Periodic",
        "Attendance",
        "To-Do",
        "Random Wheel",
        "Scoreboard",
        "Math Graph",
      ],
    },
    cloud: {
      t: "Cloud power. Offline backup.",
      d: "Full AI in cloud mode. When the connection drops, keep teaching with limited voice recording or text.",
    },
    share: {
      t: "Present, share, export",
      d: "Multiple pages, undo and redo, zoom and one-tap sharing.",
    },
    pen: {
      t: "Still a whiteboard",
      d: "Pen, shapes, text and images by touch. Voice comes first — never the only way.",
    },
    cloudOn: "Cloud",
    cloudOff: "Offline",
  },
  story: {
    pill: "03",
    kicker: "Why we built it",
    title: "It started with one teacher.",
    p1: "Pak Dadan M. Ramdhan — “Pak Damar” — teaches Bahasa Indonesia at SMPN 20 Bandung. He lives with a disability and has never stopped teaching.",
    p2: "He became the starting point of all our research. What if the board adapted to the teacher, instead of the other way around?",
    name: "PAK DAMAR",
    role: "Bahasa Indonesia teacher",
    sticker: "Voice-first is access.",
    tagline: "TRIDO: Together building inclusive education",
  },
  award: {
    pill: "04",
    kicker: "Recognition",
    title: "2nd place in the world.",
    sub: "Gemma 4 Good Hackathon by Google — a challenge to build with Gemma 4 for real-world impact.",
    timeline: [
      {
        t: "The Challenge",
        d: "Targeting cognitive accessibility and voice-first interaction with lightweight AI models.",
      },
      {
        t: "Built for Humans",
        d: "Designed around real classroom dynamics and daily workflows with voice-controlled canvas.",
      },
      {
        t: "Global Recognition",
        d: "TRIDO: AI-based voice smartboard. Presented in 2026.",
      },
    ],
    stats: [
      { n: "2", s: "nd", l: "place worldwide" },
      { n: "11", s: "", l: "classroom widgets" },
      { n: "2", s: "", l: "languages" },
      { n: "100", s: "%", l: "voice-controlled" },
    ],
    by: "Presented by",
  },
  faq: {
    pill: "05",
    kicker: "FAQ",
    title: "Good questions.",
    items: [
      {
        q: "Do I need special hardware?",
        a: "TRIDO runs in the browser. Any interactive display, laptop or tablet with a microphone will do.",
      },
      {
        q: "Which languages does it understand?",
        a: "English and Bahasa Indonesia — and the whole interface switches with one tap.",
      },
      {
        q: "What if the internet drops?",
        a: "Offline mode keeps the basics going: record your voice or type. Cloud mode brings the full AI back when you reconnect.",
      },
      {
        q: "Is it voice only?",
        a: "No. Pen, shapes, text and images work by touch too. Voice is first, never the only way.",
      },
      {
        q: "How can my school try it?",
        a: "Request a demo below and we'll get in touch.",
      },
    ],
  },
  cta: {
    pill: "06",
    title: "Bring TRIDO to your classroom.",
    sub: "Leave your email and we'll arrange a live demo — in English or Bahasa Indonesia.",
    placeholder: "you@school.id",
    button: "Request a demo",
    thanks: "Thank you — let's talk!",
    thanksSub: "We'll be in touch very soon.",
    invalid: "Please enter a valid email.",
  },
  footer: {
    rights: "© 2026 TRIDO. All rights reserved.",
    top: "Back to top",
  },
};

export type Content = typeof content;
export default content;
