export const content = {
  nav: {
    how: "How it works",
    features: "Chaos Engine",
    story: "Why Exur",
    award: "Gemma 4 Core",
    faq: "FAQ",
    cta: "Launch Exur",
    menu: "Menu",
  },
  hero: {
    h1a: "Design it.",
    h1b: "Break it. Fix it.",
    sub: "Exur is the AI Staff Architect that designs your system, attacks it like a chaos engineer, and hardens it before you write code.",
    cta1: "Launch Exur",
    cta2: "Watch Attack Demo",
    meta: ["Google Gemma 4 Core", "Deterministic Blast Radius", "ElevenLabs Verdict Voice"],
    try: "Try a system scenario",
  },
  demo: {
    classroom: "Chaos Engineering Canvas",
    cloud: "Gemma 4 Active",
    assistant: "AI Staff Architect",
    share: "Incident Log",
    save: "Hardening Summary",
    teacher: "Chaos Engineer",
    classLead: "Staff Systems Architect",
    ready: "System Ready for Attack",
    readySub: "Describe a system or select a scenario",
    listening: "Gemma 4 Identifying SPOFs...",
    listeningSub: "Locating single points of failure",
    thinking: "Simulating 3 AM Chaos Attack...",
    thinkingSub: "Propagating cascade failure through nodes",
    done: "System Hardened & Verified",
    doneSub: "Resilience score improved: 31 ➔ 82",
    tabs: ["Food Delivery", "E-Commerce Core", "Payment Gateway"],
    say: [
      "A food delivery app with mobile clients, one API server, a primary database, Redis cache, payment gateway, and notification worker",
      "An e-commerce checkout with web clients, auth service, order queue, primary database, and inventory cache",
      "A UPI payment gateway with merchant API, token vault, core banking ledger, and webhook dispatcher",
    ],
    mm: {
      title: "Cascade Failure Propagation Graph",
      center: "API Server",
      elements: "Attack Vector",
      inner: "Primary DB",
      innerSub: "OOM Crash · Saturated Pool",
      outer: "Payment Worker",
      outerSub: "Deadlock · Blocked Thread",
      types: "Hardened Tier",
      old: "Read Replica",
      oldSub: "Survives · Read Traffic Decoupled",
      modern: "Circuit Breaker",
      modernSub: "Tripped · Prevents Client Cascade",
    },
    doc: {
      label: "3 AM Incident Timeline",
      title: "Primary DB Saturated Cascade",
      intro:
        "At 03:14 UTC, a sudden 4x traffic surge saturated the single primary database connection pool, causing cascade timeout across dependent workers.",
      h1: "1. Cascade Blast Radius",
      formula: "Primary DB (Crash) ➔ Payment Worker (Deadlock) ➔ Mobile Client (504 Crash)",
      h2: "2. Hardening Fixes Applied by Gemma 4",
      items: [
        ["Read Replica Added", "Offloaded 70% of read queries from primary instance"],
        ["Async Queue Decoupled", "Buffered incoming order spikes during database latency spikes"],
        ["Circuit Breaker Tripped", "Prevented 504 timeouts from cascading back to mobile users"],
      ],
    },
    tools: {
      timer: "Resilience Score",
      score: "Component Status",
      teams: ["Primary DB (Crash ➔ Replicated)", "API Gateway (Failed ➔ Protected)", "Order Queue (Overflow ➔ Buffered)"],
    },
  },
  marquee: [
    "Primary database connection pool exhausted",
    "Redis eviction cascade under peak writes",
    "Payment gateway 504 gateway timeout",
    "Worker thread starvation memory overflow",
    "Single point of failure detected in API gateway",
    "Circuit breaker tripped to isolate database failure",
    "Read replica promoted during simulated crash",
    "Asynchronous queue absorbs 10x traffic spike",
    "Resilience score improved from 31 to 82",
    "Zero hallucinated metrics · deterministic model",
  ],
  how: {
    pill: "01",
    kicker: "How it works",
    title: "Design. Attack. Harden.",
    steps: [
      {
        t: "Design",
        d: "Describe your system in plain words. Gemma 4 parses microservices, databases, and dependencies into a live interactive graph.",
      },
      {
        t: "Attack",
        d: "Exur plays chaos engineer: it picks the deadliest single point of failure and simulates the 3 AM cascade failure step by step.",
      },
      {
        t: "Harden",
        d: "Exur patches vulnerabilities with replicas, queues, and circuit breakers, re-running the same attack to verify survival.",
      },
    ],
  },
  features: {
    pill: "02",
    kicker: "Chaos Engine",
    title: "Stress-test before building.",
    mm: {
      t: "Live Topology Graph",
      d: "Gemma 4 maps your services, databases, and dependencies on screen without manual dragging.",
    },
    doc: {
      t: "3 AM Incident Timeline",
      d: "Watch failures propagate step-by-step with real timestamps, cascading blast radius, and root-cause logs.",
    },
    widgets: {
      t: "11 Resilience Tools",
      d: "Deterministic fault-tolerance verification and blast radius scoring.",
      list: [
        "Failure Propagation",
        "Resilience Score",
        "SPOF Detector",
        "Circuit Breaker",
        "Read Replica",
        "Deadlock Audit",
        "Queue Decoupler",
        "Blast Radius Gauge",
        "Post-Mortem Log",
        "Health Inspector",
        "Auto-Hardener",
      ],
    },
    cloud: {
      t: "Deterministic Engine",
      d: "Gemma 4 handles deep architectural reasoning. Deterministic graph logic simulates the failure cascade with zero hallucinated data.",
    },
    share: {
      t: "Hardening Summary",
      d: "Export the before/after resilience scorecard and hardening post-mortem directly to markdown.",
    },
    pen: {
      t: "Staff Architect Voice",
      d: "ElevenLabs speaks the attack announcement, failure summary, and final verdict in a seasoned tech-lead tone.",
    },
    cloudOn: "Simulating",
    cloudOff: "Hardened",
  },
  story: {
    pill: "03",
    kicker: "Why Exur",
    title: "Every outage was a design.",
    p1: "Every massive tech outage — from major cloud zone drops to food delivery crashes during peak hours — traces back to a system design nobody stress-tested.",
    p2: "Exur stress-tests your architecture at design time. It breaks your system safely in simulation so it never breaks in production.",
    name: "EXUR CHAOS",
    role: "AI Staff Architect",
    sticker: "Attack before production.",
    tagline: "Exur: AI Staff Architect powered by Google Gemma 4",
  },
  award: {
    pill: "04",
    kicker: "Google Gemma 4",
    title: "Powered by Gemma 4.",
    sub: "Built for the Hacktoberfest 'Best Use of Gemma 4' challenge using Google's lightweight open-weight model through the Gemini API.",
    timeline: [
      {
        t: "Gemma 4 Architecture Engine",
        d: "Extracts microservices, databases, and dependencies from plain text descriptions.",
      },
      {
        t: "Vulnerability & SPOF Analysis",
        d: "Gemma 4 discovers the deadliest failure vectors and generates concrete architectural hardening patches.",
      },
      {
        t: "Deterministic Failure Propagation",
        d: "Deterministic graph model computes blast radius and before/after resilience scores.",
      },
    ],
    stats: [
      { n: "31", s: "➔82", l: "Resilience Score" },
      { n: "100", s: "%", l: "Open Source (MIT)" },
      { n: "0", s: "", l: "Hallucinated Load Tests" },
      { n: "Gemma", s: "4", l: "Core Reasoning Model" },
    ],
    by: "Core technologies",
  },
  faq: {
    pill: "05",
    kicker: "FAQ",
    title: "Good questions.",
    items: [
      {
        q: "Does Exur run real load tests against live servers?",
        a: "No. Exur is an architecture-time design tool. It uses a deterministic failure propagation model on your architecture graph to map blast radius and dependencies before you write code.",
      },
      {
        q: "What does Google Gemma 4 do in Exur?",
        a: "Gemma 4 designs the system topology, analyzes the deadliest single point of failure (SPOF), and generates the architectural hardening fixes (replicas, queues, circuit breakers).",
      },
      {
        q: "How is the resilience score calculated?",
        a: "The score is calculated deterministically by evaluating single points of failure, redundancy ratios, and isolated blast radii before and after hardening.",
      },
      {
        q: "What role does ElevenLabs play?",
        a: "ElevenLabs speaks for 3 short, impactful moments: the attack announcement, the failure summary, and the final verdict in a seasoned tech-lead voice.",
      },
      {
        q: "Can I use Exur if I'm not a cloud architect?",
        a: "Yes. You describe your system in plain everyday words (for example: 'a food delivery app with an API, database, cache, and payment worker') and Exur handles the rest.",
      },
    ],
  },
  cta: {
    pill: "06",
    title: "Stress-test your system.",
    sub: "Describe your app. Watch Exur attack it, break it, and harden it.",
    placeholder: "engineer@company.com",
    button: "Launch Exur",
    thanks: "Welcome to Exur!",
    thanksSub: "Ready to stress-test your system design.",
    invalid: "Please enter a valid email address.",
  },
  footer: {
    rights: "© 2026 Exur (exur.in). Built with Google Gemma 4.",
    top: "Back to top",
  },
};

export type Content = typeof content;
export default content;
