export const content = {
  nav: {
    how: "How it works",
    features: "Capabilities",
    story: "Why Exur",
    award: "Open Architecture",
    faq: "FAQ",
    cta: "Launch Canvas",
    menu: "Menu",
  },
  hero: {
    h1a: "Speak systems.",
    h1b: "Exur builds.",
    sub: "Exur is the voice-first system design canvas. Speak your technical requirements — Exur renders the live topology graph, drafts the RFC spec, detects bottlenecks, and audits cloud costs in real time.",
    cta1: "Launch Architecture Canvas",
    cta2: "Watch Live Demo",
    meta: ["Voice-First Whiteboarding", "Stateful Graph Memory", "Gemma 4 + ElevenLabs"],
    try: "Try it — choose an architecture",
  },
  demo: {
    classroom: "System Design Canvas",
    cloud: "Live Inference",
    assistant: "Staff Architect AI",
    share: "Share RFC",
    save: "Export ADR",
    teacher: "Architect",
    classLead: "Lead Systems Engineer",
    ready: "Architecture Engine Ready",
    readySub: "Voice ready · choose an architecture",
    listening: "Listening to Requirements",
    listeningSub: "Speak system requirements naturally",
    thinking: "Gemma 4 planning topology...",
    thinkingSub: "Analyzing protocols & bottlenecks",
    done: "System Topology Rendered",
    doneSub: "Inspect graph, RFC spec & cost gauges",
    tabs: ["Event Pipeline", "FinTech Payment Core", "Video Transcoder"],
    say: [
      "Design an IoT event streaming pipeline with Kafka broker and TimescaleDB",
      "Architect a zero-downtime UPI payment gateway with Redis and Postgres",
      "Build a video streaming platform with S3 chunk storage and CDN distribution",
    ],
    mm: {
      title: "Real-Time Event Ingestion Topology",
      center: "API Gateway",
      elements: "Ingestion Tier",
      inner: "Kafka Broker",
      innerSub: "Partitioned event log",
      outer: "TimescaleDB",
      outerSub: "Cold time-series storage",
      types: "Processing Tier",
      old: "Worker Cluster",
      oldSub: "Kubernetes auto-scale",
      modern: "Redis Cache",
      modernSub: "In-memory state store",
    },
    doc: {
      label: "System Design RFC-104",
      title: "Distributed Event Ingestion Spec",
      intro:
        "High-throughput event streaming pipeline designed for 100,000 writes/second with sub-50ms p99 latency guarantees.",
      h1: "1. Throughput & Capacity Formula",
      formula: "100k events/sec × 1KB = 100 MB/sec ingestion bandwidth",
      h2: "2. Architectural Guarantees",
      items: [
        ["Kafka Ingestion", "3x replica factor with at-least-once delivery"],
        ["Hot Cache (Redis)", "15-minute TTL for active telemetry deduplication"],
        ["Cold Tier (TimescaleDB)", "Automated chunk compression after 48 hours"],
      ],
    },
    tools: {
      timer: "Latency Benchmark",
      score: "Monthly Cloud Cost",
      teams: ["DigitalOcean ($140/mo)", "AWS ($820/mo)", "GCP ($760/mo)"],
    },
  },
  marquee: [
    "Kafka cluster with 3 brokers",
    "Redis cluster with sentinel failover",
    "PostgreSQL read replicas with PgBouncer",
    "Kubernetes ingress with TLS termination",
    "RabbitMQ dead letter exchange queue",
    "Distributed tracing with OpenTelemetry",
    "Object storage with multi-region CDN",
    "TimescaleDB hypertable for metrics",
    "Elasticsearch cluster for full-text query",
    "gRPC microservices with Envoy service mesh",
  ],
  how: {
    pill: "01",
    kicker: "How it works",
    title: "Voice to topology.",
    steps: [
      {
        t: "Speak",
        d: "Press the mic and describe your backend requirements, throughput goals, and storage layers.",
      },
      {
        t: "Reason & Audit",
        d: "Google Gemma 4 extracts services, routes protocols, and spots single points of failure (SPOFs).",
      },
      {
        t: "Synthesize & Render",
        d: "The live SVG topology animates on screen, ElevenLabs voices the architectural critique, and Backboard persists memory.",
      },
    ],
  },
  features: {
    pill: "02",
    kicker: "Capabilities",
    title: "Architecture on command.",
    mm: {
      t: "Topology Graphs on Command",
      d: "Describe microservices, brokers, and databases. Exur lays out nodes, protocols, and data flows with zero manual dragging.",
    },
    doc: {
      t: "Automated RFC Documents",
      d: "Structured technical design documents with throughput formulas, latency budgets, and failover strategies ready to export.",
    },
    widgets: {
      t: "11 Engineering Tools",
      d: "Ask for a cloud benchmark tool and it renders directly on the canvas.",
      list: [
        "Cloud Cost Calculator",
        "p99 Latency Gauge",
        "SPOF Detector",
        "Throughput Sizer",
        "ADR Logger",
        "Database Comparer",
        "Bandwidth Sizer",
        "Protocol Matrix",
        "API Schema",
        "Cache Sizer",
        "Failover Matrix",
      ],
    },
    cloud: {
      t: "Stateful Agent Memory",
      d: "Powered by Backboard.io. Exur remembers past architectural decisions and constraints across design iterations.",
    },
    share: {
      t: "Export RFCs & Diagrams",
      d: "Export to Mermaid.js, SVG, or Markdown RFCs with one click.",
    },
    pen: {
      t: "Multi-Modal Whiteboard",
      d: "Touch, stylus, or voice. Voice comes first, but you can always drag, draw, and reposition components manually.",
    },
    cloudOn: "Connected",
    cloudOff: "Cached",
  },
  story: {
    pill: "03",
    kicker: "Why Exur",
    title: "Never drag boxes again.",
    p1: "Every senior engineer knows the frustration of whiteboarding in tools built for 2012. You spend 80% of your time aligning rectangles and only 20% reasoning about distributed systems.",
    p2: "Exur gives engineers a voice-first copilot that thinks like a Principal Staff Architect — synthesizing topologies, calculating capacity, and stress-testing edge cases in real time.",
    name: "EXUR CORE",
    role: "Voice Architecture Engine",
    sticker: "Voice is the fastest CLI.",
    tagline: "Exur: Open-Source Voice Architecture Canvas",
  },
  award: {
    pill: "04",
    kicker: "Architecture",
    title: "Pure open weight.",
    sub: "Built for Hacktoberfest & PyData with Google Gemma 4, Backboard.io, and ElevenLabs.",
    timeline: [
      {
        t: "Gemma 4 Reasoning",
        d: "Lightweight open-weight model for zero-hallucination topology extraction and bottleneck auditing.",
      },
      {
        t: "Backboard Memory Layer",
        d: "Stateful architectural graph memory keeping track of past constraints and ADRs across sessions.",
      },
      {
        t: "ElevenLabs Voice Engine",
        d: "Low-latency conversational voice synthesizing real-time staff architect feedback and audio debriefs.",
      },
    ],
    stats: [
      { n: "4", s: "", l: "Gemma 4 Reasoning" },
      { n: "100", s: "%", l: "Open Source (MIT)" },
      { n: "<40", s: "ms", l: "p99 Voice Latency" },
      { n: "0", s: "", l: "Manual Dragging" },
    ],
    by: "Built with",
  },
  faq: {
    pill: "05",
    kicker: "FAQ",
    title: "Good questions.",
    items: [
      {
        q: "How does Exur generate system diagrams from voice?",
        a: "Exur streams your audio input to Google Gemma 4, which parses entities, connections, and protocols into a structured topological graph rendered in real time.",
      },
      {
        q: "How does Backboard help in architecture design?",
        a: "Backboard provides persistent vector memory for your system design sessions. It remembers your previous decisions (e.g. choice of database or replication factor) so subsequent changes preserve context.",
      },
      {
        q: "Can I export the diagrams to my team's documentation?",
        a: "Yes. You can export any design as Mermaid.js, SVG, or a Markdown RFC compatible with GitHub, Notion, or Linear.",
      },
      {
        q: "What role does ElevenLabs play?",
        a: "ElevenLabs voices the Staff Architect AI feedback, critiquing your design out loud and pointing out single points of failure without taking your eyes off the canvas.",
      },
      {
        q: "Is Exur open source?",
        a: "Yes, Exur is completely open source under the MIT license.",
      },
    ],
  },
  cta: {
    pill: "06",
    title: "Build with Exur.",
    sub: "Speak your requirements and watch your system topology and technical RFC build in seconds.",
    placeholder: "engineer@company.com",
    button: "Launch Exur Canvas",
    thanks: "Welcome to Exur!",
    thanksSub: "Ready to whiteboard at the speed of thought.",
    invalid: "Please enter a valid email address.",
  },
  footer: {
    rights: "© 2026 Exur (exur.in). Open-source under MIT License.",
    top: "Back to top",
  },
};

export type Content = typeof content;
export default content;
